build: off

environment:
  matrix:
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9"
    - PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10"
    - PYTHON: "C:\\Python311"
      PYTHON_VERSION: "3.11"

    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10"
      PYTHON_ARCH: "32"
      
install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install pytest

test_script:
  - python -m pytest
